// Define a type for the color object
interface Color {
  readonly name: string;
  readonly hex: string;
}

// Create a read-only array of colors
export const initialColors: readonly Color[] = [
  { name: 'Red', hex: '#FF0000' },
  { name: 'Green', hex: '#00FF00' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Dark Blue', hex: '#00008B' },
  { name: 'Light Blue', hex: '#ADD8E6' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Light Green', hex: '#E1E8EB' },
  { name: 'Chocolate', hex: '#D2691E' },
  { name: 'Dark Gray', hex: '#A9A9A9' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Indigo', hex: '#4B0082' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Lime', hex: '#00FF00' },
  { name: 'Peach Puff', hex: '#FFDAB9' },
  { name: 'Mint Cream', hex: '#F5FFFA' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Light Salmon', hex: '#FFA07A' },
  { name: 'Dark Golden Rod', hex: '#B8860B' },
  { name: 'Fire Brick', hex: '#B22222' },
  { name: 'Medium Sea Green', hex: '#3CB371' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Sandy Brown', hex: '#F4A460' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Medium Violet Red', hex: '#C71585' },
  { name: 'Lawn Green', hex: '#7CFC00' },
  { name: 'Dark Orchid', hex: '#9932CC' },
  { name: 'Light Coral', hex: '#F08080' },
  { name: 'Gainsboro', hex: '#DCDCDC' },
  { name: 'Light Slate Gray', hex: '#778899' },
  { name: 'Rosy Brown', hex: '#BC8F8F' },
  { name: 'Pale Golden Rod', hex: '#EEE8AA' },
  { name: 'Medium Slate Blue', hex: '#7B68EE' },
  { name: 'Dark Salmon', hex: '#E9967A' },
  { name: 'Light Cyan', hex: '#E0FFFF' },
  { name: 'Antique White', hex: '#FAEBD7' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Blue Sky', hex: '#a0d9ef' },
  { name: 'Brown', hex: '#895129' },
] as const;