export const FORM_TYPES = {
  SENDTRANSFER: 1,
    RECEIPT: 2,
  PAYMENT: 3,
  EXCHANGEUSD: 4,
  EXCHANGEALL:5,
INCOMETRANSFER: 6,
PAIDINCOMETRANSFER: 7,
 FIRSTBALANCE: 8,
 QAID: 9,
  REPORTS: 10,
  OPENING_BALANCE_TYPE_ID:99,
} as const;

export type FormTypeId = typeof FORM_TYPES[keyof typeof FORM_TYPES];